# Generated by Django 3.1.7 on 2021-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
    ]
