# Generated by Django 3.1.7 on 2021-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20210302_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Slug must be like - tag!', max_length=15, unique=True),
        ),
    ]
