# Generated by Django 3.1.7 on 2021-03-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20210302_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
    ]
