# Generated by Django 3.1.7 on 2021-03-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210302_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/Y%/%m/%d/'),
        ),
    ]
